name: Build WhatsAppEmoji

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes zopfli pngquant
        python -m pip install --upgrade pip
        python -m pip install -r https://raw.githubusercontent.com/Swakshan/emoji-builder/main/requirements.txt
    - name: Build WhatsAppEmoji
      run: |
        make -j
        make install
    - name: Upload .ttf file
      uses: actions/upload-artifact@v2
      with:
        name: WhatsAppEmoji
        path: build/WhatsAppEmoji.ttf
